name: check

on:
  pull_request:
    branches: [ "main" ]

env:
  LOCAL_BASE_IMAGE: android-sdk:tools

jobs:
  check_tools:
    runs-on: ubuntu-latest
    env:
      ANDROID_SDK_TOOLS_VERSION: 9123335
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - uses: docker/build-push-action@v3
        with:
          context: .
          file: ./tools/Dockerfile
          platforms: linux/amd64
          build-args: |
            ANDROID_SDK_TOOLS_VERSION=${{ env.ANDROID_SDK_TOOLS_VERSION }}
          tags: ${{ env.LOCAL_BASE_IMAGE }}
          outputs: type=docker,dest=/tmp/tools.tar

      - uses: actions/upload-artifact@v3
        with:
          name: tools
          path: /tmp/tools.tar

  check_sdk:
    needs: ["check_tools"]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: 33
            build-tools: 33.0.1
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2

      - uses: actions/download-artifact@v3
        with:
          name: tools
          path: /tmp

      - run: |
          docker load --input /tmp/tools.tar
          docker buildx use default

      - uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          build-args: |
            BASE_IMAGE=${{ env.LOCAL_BASE_IMAGE }}
            ANDROID_PLATFORM_VERSION=${{ matrix.platform }}
            ANDROID_BUILD_TOOLS_VERSION=${{ matrix.build-tools }}
          tags: android-sdk:${{ matrix.platform }}